services:
  db:
    image: postgres:15-alpine
    container_name: medium_db
    restart: always
    environment:
      POSTGRES_USER: medium_user
      POSTGRES_PASSWORD: medium_password
      POSTGRES_DB: medium_clone
    # Mengatur PostgreSQL untuk memanfaatkan RAM yang lega
    command: 
      - "postgres"
      - "-c"
      - "shared_buffers=1GB"    # Gunakan 1GB RAM khusus untuk cache database
      - "-c"
      - "max_connections=50"    # Batasi max koneksi DB di angka 50 agar aman
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1.2'        # Berikan jatah maksimal 1.2 Core untuk DB
          memory: 4G         # Jatah RAM sangat lega (4 GB)
        reservations:
          cpus: '0.5'
          memory: 1G
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: medium_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 64M

  minio:
    image: minio/minio:latest
    container_name: medium_minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: medium_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.8'        # Sisa 0.8 Core dialokasikan untuk Backend Golang
          memory: 1G         # 1 GB RAM sudah sangat mewah untuk Golang
        reservations:
          cpus: '0.2'
          memory: 128M
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=medium_user
      - DB_PASSWORD=medium_password
      - DB_NAME=medium_clone
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8080
      - JWT_SECRET=super_secret_jwt_key_ubah_ini_di_productionqwertyuiopasdfghjkl0987654erfghjkbvczxcv0987654wdfghjnbfde34567uikjn
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-AQ.Ab8RN6K7V-XcsehIPKddx5SKtDmyZ1cKNE_7tOCVcRFAdzYNHg}
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin123}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME:-medium-uploads}
      - MINIO_USE_SSL=false
      - MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL:-http://localhost:9000}
    depends_on:
      - db
      - redis
      - minio

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8080/api}
        - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}
    container_name: medium_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8080/api}
      - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}
      - INTERNAL_API_URL=http://backend:8080/api
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M

volumes:
  pgdata:
  redisdata:
  minio_data:
